CREATE TABLE USUARIO (
    ID_USUARIO SERIAL NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    LOGIN VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    TP_USUARIO VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(60) NULL,
    CONSTRAINT USUARIO_PK PRIMARY KEY (ID_USUARIO)
);

ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_UK_LOGIN UNIQUE (LOGIN);
-- ALTER COLUMN ID_USUARIO SET DEFAULT nextval('USUARIO_ID_USUARIO_SEQ'::regclass);