CREATE TABLE CONTA
(
    ID_CONTA       SERIAL         NOT NULL,
    ID_USUARIO     INTEGER        NOT NULL,
    COD_BANCO      VARCHAR(4)     NOT NULL,
    COD_AGENCIA    VARCHAR(25)    NOT NULL,
    DIGITO_AGENCIA CHAR(1)        NOT NULL,
    COD_CONTA      VARCHAR(25)    NOT NULL,
    DIGITO_CONTA   CHAR(1)        NOT NULL,
    SALDO          DECIMAL(10, 2) NOT NULL,
    CONSTRAINT CONTA_PK PRIMARY KEY (ID_CONTA)
);

ALTER TABLE CONTA
    ADD CONSTRAINT USUARIO_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE CONTA
    ADD CONSTRAINT CONTA_UK_COD_AGENCIA_COD_CONTA UNIQUE (COD_AGENCIA, COD_CONTA);



