CREATE TABLE TRANSACAO
(
    ID_TRANSACAO       SERIAL,
    ID_CONTA_ORIGEM    INTEGER,
    ID_CONTA_DESTINO   INTEGER,
    TIPO_TRANSACAO_FIN CHAR,
    VALOR_TRANSACAO    DECIMAL(10, 2),
    DATA_TRANSACAO     TIMESTAMP,
    TAXA_CAMBIO        DECIMAL(10, 2),
    TIPO_DESPESA       VARCHAR(25),
    STATUS_TRANSACAO   CHAR,
    CONSTRAINT TRANSACAO_PK PRIMARY KEY (ID_TRANSACAO),
    FOREIGN KEY (ID_CONTA_ORIGEM) REFERENCES CONTA (ID_CONTA),
    FOREIGN KEY (ID_CONTA_DESTINO) REFERENCES CONTA (ID_CONTA)
);